/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::rubberband<1>, scriptnode::wrap::illegal_poly<project::rubberband<1>>>();
		registerPolyNode<project::reverb_faust<1>, scriptnode::wrap::illegal_poly<project::reverb_faust<1>>>();
		registerPolyNode<project::pitch_shifter_faust<1>, scriptnode::wrap::illegal_poly<project::pitch_shifter_faust<1>>>();
		registerPolyNode<project::Deathrattle_network<1>, wrap::illegal_poly<project::Deathrattle_network<1>>>();
		registerPolyNode<project::pitchShifter<1>, wrap::illegal_poly<project::pitchShifter<1>>>();
		registerPolyNode<project::reverb<1>, wrap::illegal_poly<project::reverb<1>>>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


