/** Autogenerated Main.cpp. */

// ================================| Include only the DSP files  |================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ==========================| Now we can add the rest of the codebase |==========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// ======================================| Project Factory |======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -------------------------------------------------------------------
		
		registerPolyNode<project::tuner<1>, project::tuner<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::transpose<1>, project::transpose<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::ringmod<1>, project::ringmod<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::reverb<1>, project::reverb<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::preprocess<1>, project::preprocess<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::postprocess<1>, project::postprocess<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::overdrive<1>, project::overdrive<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::gate<1>, project::gate<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::delay<1>, project::delay<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::chorus<1>, project::chorus<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::amp<1>, project::amp<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::cab<1>, wrap::illegal_poly<project::cab<1>>>();
		registerPolyNode<project::chug<1>, wrap::illegal_poly<project::chug<1>>>();
		registerPolyNode<project::click<1>, wrap::illegal_poly<project::click<1>>>();
		registerPolyNode<project::octave<1>, wrap::illegal_poly<project::octave<1>>>();
		registerPolyNode<project::pick<1>, wrap::illegal_poly<project::pick<1>>>();
		registerDataNode<project::tuner_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


