/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "octave_faust.h"
#include "reverb_faust.h"
#include "rubberband.h"

// Include compiled network files ------------------

#include "amp.h"
#include "cab.h"
#include "chug.h"
#include "octaveFaust.h"
#include "pick.h"
#include "pitchDetection_networkdata.h"
#include "reverb.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

