/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include embedded audio data ---------------------

#include "embedded_audiodata.h"
// Include third party header files ----------------

#include "amp.h"
#include "cabDesigner.h"
#include "chorus.h"
#include "clipper.h"
#include "delay.h"
#include "gate.h"
#include "overdrive.h"
#include "reverb.h"
#include "ringmod.h"
#include "transpose.h"
#include "tuner.h"

// Include compiled network files ------------------

#include "cab.h"
#include "cabDesignerInput_networkdata.h"
#include "cabDesignerNetwork.h"
#include "chug.h"
#include "click.h"
#include "DCFilterOutput.h"
#include "InterSamplePeakBlocker.h"
#include "octave.h"
#include "pick.h"
#include "tuner_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

