namespace project
{

struct pitchDetection_networkdata: public scriptnode::dll::InterpretedNetworkData
{
	String getId() const override
	{
		return "pitchDetection";
	}
	bool isModNode() const override
	{
		return false;
	}
	String getNetworkData() const override
	{
		return "725.nT6K8C1pLzkE.XBHlYB3xhd.uzDILJtN4DoOtQziJEHJWADKt4ixkZfXLF65hHhnEgEJklE.aAPW.bE63gLiCwNO.IrMRyNa8ueVrFu.D5FLeVzBt4.z70asQNeff2XEU+oLdmTKWgl2biW7oRuVwI7l+KpEcyQMGps0WCdRkWq+9V1Xckb7DZ1REQZtiJEj6aQ.chZdKLLBBgNeg5eq+GSZDzLtd9L3OVyuiGecBm.dphphhz6UYhRCBeunlyPyf7cfo0DvS7xymz72AKpwTdAp4IMyr6AWRyd9qYEcySDuQKddLNYzHhzQXRMdBcf6Iv0ikINkvE3unWBQhgyemdUSuJJUnnfsF3XJ2bozLLtFEjRED1bMI2mxHE9DeRk6AGRhycLb.pT4lpzjnbUTNJJUjndMooJWkpHnu.7AaOny0jhZ9BN67.tXAv9.WUv14jFQ2dDqzhOPGw5bQufEmdjPNoWfXqjt6nLufZ7wrbHlaOWRlLCD97xasdA.sCY13pgZcC7H80ec8YxjvVeMZ5.wmHFGqzRza+fEmQugmCECSZYod3GnQD6XJSAEgDDxfZ.P.APnyVY.kgJmAUxa.YreeLYW3CwM0fNKqrbRkhnV7KkpcGBfeLAcRE1bV6pRCGmeATxco6FCEfCcgh6EapkbNGwWpuV05y.KhX4mrkT0VnCF58gujMXdsXqfbfUlLA2WzahXECAt7pTgBdb75jz.nrkBkUlI8.EEmaoySEKaQ4Ww4b9OaxQb.uRT8L0Iq1YyYaDzQ2XzGcNQs54wmMH9OCEcng0MIHeIM3asKMA2DLfPFkG5kggPRHMnpCN4arf66jR2bwiVWpYyOVi.UPuW2FGQcr+YfLcBYTI4jkIp6dXmUCdJvC.jlgTDVJXYQdlA6c.Nd8zP9Jla+Evfvv.+jmScyvOFP2O8Ph+pzQDlfqJGBbWBRgNQQ4Oj5CTq.NavuJ.";
	}
};
}

